# Generated by Django 5.0.2 on 2024-03-02 07:17

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('other', 'other')], max_length=20)),
                ('contact', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='IN')),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=20)),
                ('pin_code', models.IntegerField()),
                ('profile_pic', models.ImageField(upload_to='profile_pc')),
            ],
        ),
    ]
